color0 #161313
color1 #ffb4ab
color2 #e5bdc1
color3 #d7c1c3
color4 #debfc2
color5 #e5bdc1
color6 #d7c1c3
color7 #e9e1e0
color8 #958f8f
color9 #ffb4ab
color10 #e5bdc1
color11 #d7c1c3
color12 #debfc2
color13 #e5bdc1
color14 #d7c1c3
color15 #e9e1e0

cursor                #e9e1e0
cursor_text_color     #161313
background            #161313
foreground            #e9e1e0
selection_foreground  #ccc5c5
selection_background  #4a4646
url_color             #debfc2