animations {
    enabled = yes

    # My Animations 
    bezier = overshot, 0.25, 0.99, 0.29, 1.1
    bezier = anotherOne, 0.05, 0.9, 0.1, 1.05
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winIn, 0.1, 1.1, 0.1, 1.1
    bezier = winOut, 0.3, -0.3, 0, 1
    bezier = liner, 1, 1, 1, 1

    animation = windows, 1, 6, overshot, popin 80%
    animation = windowsIn, 1, 4, winIn, popin 80%
    animation = windowsOut, 1, 7, anotherOne, popin 80%
    animation = windowsMove, 1, 4, anotherOne, popin 75%
    animation = border, 1, 10, default
    animation = borderangle, 1, 200, default, loop
    animation = fade, 1, 10, default
    animation = workspaces, 1, 8, overshot, slide
}

