# All Configs
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/startup.conf
source = ~/.config/hypr/windowrule.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/visuals.conf
source = ~/.config/hypr/animations.conf


