# Monitors Conf
monitor=DP-1, 3440x1440@180, 1920x0, 1
monitor=DP-2, 1920x1080@165, 0x0, 1

# env Hyprland
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SESSION_DESKTOP, Hyprland
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = ~/.config/hypr/xdg-portal-hyprland
env = MOZ_DISABLE_RDD_SANDBOX,1
env = MOZ_ENABLE_WAYLAND,1
#env = QT_STYLE_OVERRIDE,kvantum
env = QT_QPA_PLATFORMTHEME,qt6ct
env = HYPRCURSOR_THEME,catpucccin-mocha-mauve-cursors
env = HYPRCURSOR_SIZE,32

# External Config
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/startup.conf
source = ~/.config/hypr/windowrule.conf
# Pywal Color Scheme 
source = ~/.cache/wal/hyprland-colors.conf
# Keyboard Layout
input {
    kb_layout = it,us
    kb_options=grp:alt_space_toggle

    numlock_by_default = true

    follow_mouse = 1
    
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

general {
    # Windows Layout

    gaps_in = 12
    gaps_out = 15
    border_size = 6
    col.active_border = $color4 $color3 45deg
    no_border_on_floating = false
    layout = dwindle
    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false
}

decoration {
    # Window Decoration

    rounding = 16
    
    blur {
        enabled = true
        size = 5
      	passes = 2
        xray = true
    }
    inactive_opacity = 0.7
    fullscreen_opacity = 1.0
}

animations {
    enabled = yes

    # My Animations 
    bezier = overshot, 0.25, 0.99, 0.29, 1.1
    bezier = dramatic, 0.6, 0.05, 0.5, 0.95

    animation = windows, 1, 6, overshot, slide
    animation = border, 1, 10, default
    animation = borderangle, 1, 200, default, loop
    animation = fade, 1, 10, default
    animation = workspaces, 1, 8, overshot, slide
}

dwindle { #Default from the OG Hyprland Conf
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

misc { #Other Settings
    
    disable_hyprland_logo = false
    disable_splash_rendering = false
    mouse_move_enables_dpms = true
    vfr = true
    vrr = 1
    animate_manual_resizes = true
    mouse_move_focuses_monitor = true
    enable_swallow = true
}

plugin {
    hyprbars {
        bar_height = 32
        bar_color = rgb(171717)
        col.text = $foreground
        bar_text_size = 12
        bar_text_font = Jetbrains Mono Nerd Font Mono Bold
        bar_button_padding = 10
        bar_padding = 15
        bar_precedence_over_border = true
        bar_buttons_alignment = left
        icons_on_hover = true
        bar_blur = true
        hyprbars-button = rgb(ff5f56), 15, , hyprctl dispatch killactive
        hyprbars-button = rgb(ffbd2e), 15, , hyprctl dispatch togglefloating
        hyprbars-button = rgb(27c93f), 15, , hyprctl dispatch fullscreen 2
        on_double_click = hyprctl dispatch fullscreen 1
   }

   hyprfoci {
		# can be from -1 to 1, will be
			# dynamic ratio with the window instead.
			# recommend fixed size for image as dynamic can look weird
			# leave one as 0 to keep original image ratio (image only)
		# width, height
		size = 100, 0 			

		# shift down right (can be from -1 to 1, similarly)
		pos = 0, -50

		#0: left/top, 1: middle, 2: down/right
		origin = 1, 0 

        # path to a directory with both.png, left.png, right.png
		# Absolute path is needed (~ for home directory is fine)
		imgs = /home/mera/Immagini/bongo/ 
	}

  hyprtrails {
    color = rgb(8839EF)
  }
}

