### Permissions
ecosystem:enforce_permissions = true
permission = /usr/bin/hypr-dock, screencopy, allow
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
permission = /var/cache/hyprpm/mera/hyprland-plugins/hyprbars.so, plugin, allow
permission = /var/cache/hyprpm/mera/hyprland-plugins/hyprtrails.so, plugin, allow
permission = /var/cache/hyprpm/mera/Hyprspace/Hyprspace.so, plugin, allow
permission = /var/cache/hyprpm/mera/dynamic-cursors/dynamic-cursors.so, plugin, allow
