# Startup
exec-once = dicons &
exec-once = hypr-dock &
exec-once = pypr &
exec-once = systemctl pipewire restart &
exec-once = /usr/lib/polkit-kde-authentication-agent-1 &
exec-once = waybar &
exec-once = swww init &
exec-once = swww-daemon --format xrgb &
exec-once = ~/.config/hypr/scripts/wallpaper.sh init
exec-once = swww restore &
exec-once = wl-paste --type text --watch cliphist store &
exec-once = wl-paste --type image --watch cliphist store &
exec-once = swaync &
exec-once = hypridle &
exec-once = hyprpm reload &
exec-once = udiskie
