# Startup
exec-once = systemctl pipewire restart &
exec-once = /usr/lib64/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec-once = waybar &
exec-once = swww ini &
exec-once = swww-daemon --format xrgb &
exec-once = ~/.config/hypr/scripts/wallpaper.sh init
exec-once = swww restore &
exec-once = wl-paste --type text --watch cliphist store &
exec-once = wl-paste --type image --watch cliphist store &
exec-once = swaync &
exec-once = hypridle &
exec-once = udiskie &
exec-once = hyprpm reload
