# Workspaces and Opacity
windowrule = match:class firefox, workspace 1, opacity 0.80 0.80
windowrule = match:class code, workspace 2, opacity 0.90 0.90
windowrule = match:class org.telegram.desktop, workspace 3
windowrule = match:class vesktop, workspace 3
windowrule = match:class com.rtosta.zapzap, workspace 3
windowrule = match:class com.github.th_ch.youtube_music, workspace 4
windowrule = match:class org.gnome.Nautilus, workspace 5, opacity 0.85 0.85
windowrule = match:class gimp, workspace 6
windowrule = match:class affinity.exe, workspace 6
windowrule = match:class Material Maker, workspace 6, tile true
windowrule = match:title Alert!, float true
windowrule = match:class Steam, workspace 7
windowrule = match:class steam, workspace 7
windowrule = match:class net.lutris.Lutris, workspace 8
windowrule = match:class heroic, workspace 8
windowrule = match:class galaxyclient.exe, workspace 8
windowrule = match:class resolve, workspace 9
windowrule = match:class com.obsproject.Studio, workspace 10
# Size
windowrule = match:class download, size 640 480, float true
windowrule = match:title Open File, size 640 480, float true
windowrule = match:title Save File, size 640 480, float true 
# Position
windowrule = match:class org.gnome.NautilusPreviewer, float true 
windowrule = match:class file_progress, float true 
windowrule = match:class confirm, float true 
windowrule = match:class dialog, float true
windowrule = match:class error, float true
windowrule = match:class confirmreset, float true
windowrule = match:title Confirm to replace files, float true
windowrule = match:title File Operation Progress, float true
windowrule = match:class org.pulseaudio.pavucontrol, move 1300 50%, float true
# idle_inhibit
windowrule = match:class mpv, idle_inhibit focus
windowrule = match:class firefox, idle_inhibit fullscreen



