# Shell variables
# Generated by 'wal'
wallpaper='/home/mera/Immagini/Wallpapers/DarkWallpapers/ultrawide01.png'

# Special
background='#040404'
foreground='#cccccc'
cursor='#cccccc'

# Colors
color0='#040404'
color1='#605F60'
color2='#717072'
color3='#798358'
color4='#807F80'
color5='#929293'
color6='#A09F9F'
color7='#cccccc'
color8='#8e8e8e'
color9='#605F60'
color10='#717072'
color11='#798358'
color12='#807F80'
color13='#929293'
color14='#A09F9F'
color15='#cccccc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
