# Shell variables
# Generated by 'wal'
wallpaper='/home/mera/.cache/current_wallpaper.jpg'

# Special
background='#121f3a'
foreground='#eedee9'
cursor='#eedee9'

# Colors
color0='#121f3a'
color1='#9476B8'
color2='#7587AD'
color3='#9B92B3'
color4='#A792CB'
color5='#C5ACC2'
color6='#DAA4DB'
color7='#eedee9'
color8='#a69ba3'
color9='#9476B8'
color10='#7587AD'
color11='#9B92B3'
color12='#A792CB'
color13='#C5ACC2'
color14='#DAA4DB'
color15='#eedee9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
