foreground   #cccccc
background   #040404
cursor       #cccccc

color0       #040404
color8       #8e8e8e
color1       #605F60
color9       #605F60
color2       #717072
color10      #717072
color3       #798358
color11      #798358
color4       #807F80
color12      #807F80
color5       #929293
color13      #929293
color6       #A09F9F
color14      #A09F9F
color7       #cccccc
color15      #cccccc
