--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mera/.cache/current_wallpaper.jpg"

-- Special
background="#121f3a"
foreground="#eedee9"
cursor="#eedee9"

-- Colors
color0="#121f3a"
color1="#9476B8"
color2="#7587AD"
color3="#9B92B3"
color4="#A792CB"
color5="#C5ACC2"
color6="#DAA4DB"
color7="#eedee9"
color8="#a69ba3"
color9="#9476B8"
color10="#7587AD"
color11="#9B92B3"
color12="#A792CB"
color13="#C5ACC2"
color14="#DAA4DB"
color15="#eedee9"
