--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mera/Immagini/Wallpapers/DarkWallpapers/ultrawide01.png"

-- Special
background="#040404"
foreground="#cccccc"
cursor="#cccccc"

-- Colors
color0="#040404"
color1="#605F60"
color2="#717072"
color3="#798358"
color4="#807F80"
color5="#929293"
color6="#A09F9F"
color7="#cccccc"
color8="#8e8e8e"
color9="#605F60"
color10="#717072"
color11="#798358"
color12="#807F80"
color13="#929293"
color14="#A09F9F"
color15="#cccccc"
