# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#ebe1d4"

# Title color for boxes
theme[title]="#e7c26c"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#d7c5a0"

# Background color of selected item in processes box
theme[selected_bg]="#e7c26c"

# Foreground color of selected item in processes box
theme[selected_fg]="#3e2e00"

# Color of inactive/disabled text
theme[inactive_fg]="#d0c5b4"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#afcfab"

# Cpu box outline color
theme[cpu_box]="#999080"

# Memory/disks box outline color
theme[mem_box]="#999080"

# Net up/down box outline color
theme[net_box]="#999080"

# Processes box outline color
theme[proc_box]="#999080"

# Box divider line and small boxes line color
theme[div_line]="#4d4639"

# Temperature graph colors
theme[temp_start]="#d7c5a0"
theme[temp_mid]="#e7c26c"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#d7c5a0"
theme[cpu_mid]="#e7c26c"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#d7c5a0"
theme[free_mid]=""
theme[free_end]="#52452a"

# Mem/Disk cached meter
theme[cached_start]="#afcfab"
theme[cached_mid]=""
theme[cached_end]="#324d32"

# Mem/Disk available meter
theme[available_start]="#e7c26c"
theme[available_mid]=""
theme[available_end]="#5a4300"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#d7c5a0"
theme[download_mid]="#e7c26c"
theme[download_end]="#afcfab"

# Upload graph colors
theme[upload_start]="#d7c5a0"
theme[upload_mid]="#e7c26c"
theme[upload_end]="#afcfab"
